import type { AppState } from '../types'
import { today } from '../lib/dates'

export const STATE_VERSION = 1

export const emptyState = (): AppState => ({
  version: STATE_VERSION,
  onboarded: false,
  me: 'a',
  couple: {
    a: { name: '', emoji: '💗' },
    b: { name: '', emoji: '💙' },
    anniversary: today(),
    longDistance: false,
    title: 'MyCouple',
  },
  settings: {
    theme: 'rubor',
    dark: false,
    spicy: false,
    notifications: false,
    currency: '€',
    shareLocation: false,
    sync: { enabled: false, url: '', key: '', code: '' },
  },
  posts: [],
  messages: [],
  events: [],
  memories: [],
  albums: [],
  dailyAnswers: [],
  bucket: [],
  dates: [],
  lists: [],
  chores: [],
  expenses: [],
  moods: [],
  checkins: [],
  loveLangs: [],
  letters: [],
  gratitudes: [],
  countdowns: [],
  nudges: [],
  gameLog: [],
  customCards: [],
  wordleResults: [],
  wordGames: [],
  visits: [],
  locations: [],
  places: [],
  coupons: [],
  notes: [],
  nights: [],
  repairs: [],
  achievements: [],
  seenQuestions: [],
  wrappedYearsNotified: [],
  updatedAt: Date.now(),
})
